### PR TITLE
Added boost function and command

### PR DESCRIPTION
**Pull request by Kryze**

### CODE REVIEW

**Comment by singhayushh** [comment]
Thanks for your contributions. 
Stay tuned for updates to this PR

*Reviewing and testing would take around 1-2 days*

**Comment by singhayushh** [comment]
Some minor changes have been made in the raised issue. Please check #2 and confirm if any changes are further required in this PR.

**Comment by Kryze** [comment]
I think it's all good

**Review by singhayushh — COMMENTED** [review]
This is to inform that you haven't followed the message handling conventions being used throughout the project.
There were syntax errors as well in `bot.js` line 51. And we cannot merge the PR as it is.

**Pull request closed without merging**
