### PR TITLE
DM Prompt: New User Entry

### PR DESCRIPTION
**Pull request by InternetRamen**
I completed the new user entry part.

I added places where you could uncomment for logs.

Please ignore the first few commits. I accidentally committed the code with certain testing parameters. The token in config.json I added is now invalid.

### CODE REVIEW

**Comment by InternetRamen** [comment]
#7

**Comment by InternetRamen** [comment]
#7

**Comment by singhayushh** [comment]
Thanks! 
Will test and merge.

**Review by singhayushh — APPROVED** [review]
Works like a charm ⚡ 
Thank you for all your contributions!

**Pull request merged**
